# Basic
title: 似水无痕
subtitle: 个人技术博客
welcome_message: 我是一名90后的java开发者，欢迎了解更多。
description:  嗨，我是似水无痕。
creator: 似水无痕

url: "https://wanglizhi2015.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

tag_button:
    title: 分类
    description: 技术文章分类
    url: 'https://wanglizhi2015.github.io/tag/'  

# Navigation buttons in the front page.
nav:
    #- {title: 简历, description: 我的简历, url: 'https://github.com/limeii'}
    - {title: Git, description: 个人代码, url: 'https://github.com/wanglizhi2015'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: 
    # duoshuo: 
    
# Social
social:
    github: 似水无痕
    mail: 1317911756@qq.com

# Google Analytics
ga:
     id: UA-142143336-1
     host: auto

     